### ISSUE TITLE
A way to handle survey weights?

### ISSUE THREAD

**Issue by jdollman** [jamesdunham/dgo#32]
I'm looking to use the `dgo` package to estimate latent immigration opinion at the state-level using (C)CES and I noticed that there's no straightforward way to incorporate survey weights, perhaps intentionally (as in, not including that ability is a purposeful exclusion). Does this mean that, if I want to include weights, I'll need run the model _sans_ weights, get the Stan code out of resulting object, and then add the weights bit a la [this post](https://discourse.mc-stan.org/t/survey-weighted-regression/1654/37)?

Thanks beforehand!

**Comment by devincaughey** [comment]
Hi @jdollman. Thanks for your question. If I understand it correctly, the solution is as simple as specifying the `weight_name = "NAME"` argument in the `shape()` function, where "NAME" is the name of the survey weight variable in your dataset. Let me know if that works.

Devin

**Comment by jdollman** [comment]
Esteemed Modeler of Subnational Opinion Dr. Caughey,

I'm ashamed to say it, but yes. I was barking up the wrong tree, looking for the weight parameter in `dgirt()` or as a parameter I could pass to `stan()`.
